worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    keepalive_timeout 65;

    server {
        listen {{serverPort}};
        server_name {{serverAddress}};

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root html;
        }
{{for location_index, location in locations:
    {{declare location_root as cat(trim(replace(location.root, "\\", "/"), "/"), "/")}}
    {{declare location_url as cat("/", trim(location.base, "/"), when(trim(location.base, "/"), "/"))}}


    {{if location.type = 0:

        location {{location_url}} {
            return 403;
        }
    }|{elif location.type = 1:

        location {{location_url}} {
            alias '{{location_root}}';
            autoindex {{when(location.list, "on", "off")}};

        {{if location.index:

            index index.html index.php;
        }}


            location ~ "\.php$" {
                try_files $uri =404;
                include fastcgi-php.conf;
            }
        }
    }|{elif location.type = 2:

        location {{location_url}} {
            alias '{{location_root}}';
            try_files /index.php =404;
            include fastcgi-php.conf;
        }
    }|{elif location.type = 3:

        location {{location_url}} {
            alias '{{location_root}}';
            autoindex {{when(location.list, "on", "off")}};

        {{if location.index:

            index {{location.index}};
        }}

        }
    }|{elif location.type = 4:

        location {{location_url}} {
            alias '{{cat(trim(replace(phpMyAdmin.directory, "\\", "/"), "/"), "/")}}';
            autoindex off;
            index index.php;

            location ~ "\.php$" {
                try_files $uri =404;
                include fastcgi-php.conf;
            }
        }
    }|{elif location.type = 5:

        location {{location_url}} {
            alias '{{location_root}}';
            autoindex off;
            index index.php;
            try_files $uri $uri/ @name_{{location_index}}_index;

            location ~ "\.php$" {
                try_files $uri =404;
                include fastcgi-php.conf;
            }
        }

        location @name_{{location_index}}_index {
            root '{{location_root}}';
            try_files /index.php =404;
            include fastcgi-php.conf;
        }
    }}
}}

    }
}
